name: Sync Docs from splink

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout splink3_legacy_docs
        uses: actions/checkout@v2

      - name: Fetch splink repository
        run: |
          git clone --depth 1 --branch splink3 https://github.com/moj-analytical-services/splink.git splink
          cp -r splink/docs/* splinkdocs/
          rm -rf splink

      - name: Commit and push changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"
          git add .
          git commit -m "Update docs from splink repository"
          git push origin main
